### ISSUE TITLE
bitwise operations error

### ISSUE THREAD

**Issue by UmbrellaCoders** [ip2location/ip2location-lua#1]
Bitwise operations like | , <<, >>  not supoorted on lua 5.1 
getting error
' error loading module 'ip2location' from file '/usr/share/tarantool/ip2location.lua':
tarantool_1  | 	/usr/share/tarantool/ip2location.lua:131: unexpected symbol near '|'
'

**Comment by ip2location-com** [comment]
Yes, the min version of Lua supported is 5.3 due the availability of native bitwise operators.

**Comment by UmbrellaCoders** [comment]
any chance to support lua 5.1 built in in tarantool?
