### ISSUE TITLE
Support Compressed Form of IPV6

### ISSUE THREAD

**Issue by okw95** [ip2location/ip2location-lua#2]
Hope to have supported the compressed form of IPV6 in future.

**Comment by ghost** [comment]
It seems like there are a couple issues. 

This appears to handle an address with 8 hextets:

https://github.com/ip2location/ip2location-lua/blob/120dbfb344e46a442cbdbc2d3e5e00a8c7f7415c/ip2location.lua#L407

The attempts to add compressed support appeared to be commented underneath that line. I attempted to insert zeroes as placeholders for `::` in the script for testing purposes and the `checkip()` function still seems to return `R.ERROR`. The logic I am using was tested on numerous types of compressed addresses and is able to generate zeroes and leading zeroes consistently. There may be something I am overlooking or an issue with how the address is being converted or stored. Hopefully a dev can weigh in.
